---
kind: pipeline
name: default

steps:
  - name: backend
    image: golang:1.14-alpine
    enviroment:
      NETRC:
        from_secret: netrc

    commands:
      - echo $NETRC | base64 -d > ~/.netrc
      - go build
      - echo $USERNAME
      - echo "success"